# Generated by Django 5.2.3 on 2025-06-16 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navsteva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_navstevy', models.DateTimeField(default=django.utils.timezone.now)),
                ('poznamka', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=200)),
                ('datum_narozeni', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ObservationBolestiHlavy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obdobi_od', models.DateField()),
                ('obdobi_do', models.DateField()),
                ('pocet_dni_s_bolesti', models.IntegerField()),
                ('prumerna_intenzita', models.IntegerField()),
                ('navsteva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bolesti_hlavy', to='core.navsteva')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationKlepaniPrsty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnocena_koncetina', models.CharField(max_length=50)),
                ('pocet_poklepu', models.IntegerField()),
                ('doba_trvani_s', models.IntegerField()),
                ('navsteva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='klepani_prsty', to='core.navsteva')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationKrevniTlak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolicky', models.IntegerField()),
                ('diastolicky', models.IntegerField()),
                ('srdecni_frekvence', models.IntegerField()),
                ('poloha_pacienta', models.CharField(max_length=50)),
                ('navsteva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='krevni_tlak', to='core.navsteva')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationReakcniDoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_podnetu', models.CharField(max_length=50)),
                ('prumerna_doba_ms', models.IntegerField()),
                ('smerodatna_odchylka_ms', models.FloatField()),
                ('navsteva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reakcni_doba', to='core.navsteva')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationSrozumitelnostReci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencni_text', models.TextField()),
                ('wer_procento', models.FloatField()),
                ('rychlost_reci', models.FloatField()),
                ('klinicka_interpretace', models.TextField(blank=True, null=True)),
                ('navsteva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='srozumitelnost_reci', to='core.navsteva')),
            ],
        ),
        migrations.AddField(
            model_name='navsteva',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navstevy', to='core.pacient'),
        ),
    ]
