# Generated by Django 5.2.3 on 2025-06-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationbolestihlavy',
            name='prumerna_intenzita',
            field=models.IntegerField(help_text='SNOMED CT: 25064002 (Pain intensity)'),
        ),
        migrations.AlterField(
            model_name='observationkrevnitlak',
            name='diastolicky',
            field=models.IntegerField(help_text='SNOMED CT: 271650006 (Diastolic blood pressure)'),
        ),
        migrations.AlterField(
            model_name='observationkrevnitlak',
            name='srdecni_frekvence',
            field=models.IntegerField(help_text='SNOMED CT: 364075005 (Heart rate)'),
        ),
        migrations.AlterField(
            model_name='observationkrevnitlak',
            name='systolicky',
            field=models.IntegerField(help_text='SNOMED CT: 271649006 (Systolic blood pressure)'),
        ),
        migrations.AlterField(
            model_name='observationreakcnidoba',
            name='prumerna_doba_ms',
            field=models.IntegerField(help_text='SNOMED CT: 112460003 (Reaction time)'),
        ),
        migrations.AlterField(
            model_name='observationsrozumitelnostreci',
            name='rychlost_reci',
            field=models.FloatField(help_text='SNOMED CT: 1197010003 (Rate of speech)'),
        ),
    ]
